<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/05/27 11:23:31
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_jobs_on_homepage' => 10,
  'app_max_jobs_on_category' => 5,
));
