<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/05/28 09:46:24

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet_test',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
